name: Build WF
on:
  push:
    branches:
      - main
 # pull_request:
  #  branches:
 #     - main

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install
      - name: Upload Build Artifacts (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war
      - name: Notify if Build Fails
        if: failure()
        run: echo "Build failed! Please check the logs."


  Testing: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Test on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: checkstyle test
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle
      
      - name: Run Test on main branch
        if: github.ref != 'refs/heads/main'
        run: echo 'Skipping unit tests and code analysis for non-main branches'
  
  Security-Scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          scan-type: fs
          scan-ref : .
          format: 'json'
          exit-code: '0'
          output: 'trivy-report.json'

      - name: Upload Trivy scan result as artifacts (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-report.json
    
  BUILD_AND_PUSH:
     name: BUILD_AND_PUSH
     runs-on: ubuntu-latest
     needs: [build, Testing, Security-Scan]
     if:  github.ref == 'refs/heads/main'
     steps: 
      - name: Checkout code
        uses: actions/checkout@v5
        with:
         fetch-depth: 0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT